### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by pranishg** [cmtzco/steemit_upvote_bot#1]
getting error on python3 command

**Comment by pranishg** [comment]
root@shr-node-1:/home/steemit_upvote_bot# python multibot.py
  File "multibot.py", line 41
    return print("Voted!")
               ^
SyntaxError: invalid syntax
root@shr-node-1:/home/steemit_upvote_bot# python3 multibot.py
Traceback (most recent call last):
  File "multibot.py", line 1, in <module>
    from piston.steem import Steem
ImportError: No module named 'piston'
root@shr-node-1:/home/steemit_upvote_bot#
